# Monitor Zeek and Suricata logs written by sensor containers into ./data/.

[monitor:///lab/data/zeek/current/dns.log]
disabled    = false
index       = zeek
sourcetype  = zeek:dns

[monitor:///lab/data/zeek/current/conn.log]
disabled    = false
index       = zeek
sourcetype  = zeek:conn

[monitor:///lab/data/zeek/current/http.log]
disabled    = false
index       = zeek
sourcetype  = zeek:http

[monitor:///lab/data/zeek/current/ssl.log]
disabled    = false
index       = zeek
sourcetype  = zeek:ssl

[monitor:///lab/data/suricata/eve.json]
disabled    = false
index       = suricata
sourcetype  = suricata:eve
