"""Build the deployable Splunk app from per-case detections.

Walks `cases/<id>/detection/` directories, concatenates the per-case
`savedsearches.conf` and `macros.conf` into the app under
`app/default/`, generates a `detlab_cases.csv` lookup that the dashboards
read, validates the result, and packages the whole app as a `.spl` tarball
under `build/`.

Usage:
    py scripts/build_app.py
    py scripts/build_app.py --no-package    # generate confs only
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import tarfile
import tomllib
from pathlib import Path

from case_metadata import CASE_METADATA

ROOT = Path(__file__).resolve().parent.parent
CASES_DIR = ROOT / "cases"
SHARED_DIR = ROOT / "shared"
APP_DIR = ROOT / "app"
APP_DEFAULT = APP_DIR / "default"
APP_LOOKUPS = APP_DIR / "lookups"
BUILD_DIR = ROOT / "build"

GENERATED_BANNER = (
    "# !!! GENERATED BY scripts/build_app.py — DO NOT EDIT BY HAND !!!\n"
    "# Source of truth: shared/{macros,savedsearches}.conf and cases/*/detection/.\n\n"
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _case_dirs() -> list[Path]:
    return sorted(d for d in CASES_DIR.iterdir() if d.is_dir() and (d / "detection").is_dir())


def build_macros() -> str:
    """Concatenate shared/macros.conf + cases/*/detection/macros.conf."""
    chunks = [GENERATED_BANNER]
    shared = _read(SHARED_DIR / "macros.conf")
    if shared:
        chunks.append("# === shared/macros.conf ===\n" + shared.strip() + "\n\n")
    for case in _case_dirs():
        m = _read(case / "detection" / "macros.conf")
        if m:
            chunks.append(f"# === cases/{case.name}/detection/macros.conf ===\n")
            chunks.append(m.strip() + "\n\n")
    return "".join(chunks)


def build_savedsearches() -> str:
    """Concatenate cases/*/detection/savedsearches.conf and inject the
    Splunk ES Risk-Based Alerting modifier action into each stanza.

    Each case's source savedsearches.conf is hand-authored, but the RBA
    score / risk-object mapping is *metadata* (lives in
    `case_metadata.CASE_METADATA`). We bolt the `action.risk.*` lines on
    here so a single change to a score updates every saved search at
    build time, with no manual conf edits per case."""
    chunks = [GENERATED_BANNER]
    for case in _case_dirs():
        s = _read(case / "detection" / "savedsearches.conf")
        if not s:
            continue
        case_id = case.name
        rba = _rba_block_for(case_id)
        s = _inject_rba(s, rba)
        chunks.append(f"# === cases/{case.name}/detection/savedsearches.conf ===\n")
        chunks.append(s.strip() + "\n\n")
    return "".join(chunks)


def _rba_block_for(case_id: str) -> str:
    """Return the action.risk.* lines to append to each stanza for this
    case. Empty string if the case has no RBA score configured."""
    extras = CASE_METADATA.get(case_id, {})
    score = extras.get("risk_score", 0)
    if not score:
        return ""
    obj_type = extras.get("risk_object_type", "system")
    # Splunk ES expects the field name on the search results (src for
    # systems, user for accounts). Our SPL aliases set `src` everywhere
    # via the CIM helper macros; user-typed cases reuse that and rename.
    field = "user" if obj_type == "user" else "src"
    return (
        "action.risk = 1\n"
        f"action.risk.param._risk_score = {score}\n"
        f"action.risk.param._risk_object_field = {field}\n"
        f"action.risk.param._risk_object_type = {obj_type}\n"
    )


# Append RBA lines after every stanza header (and before the next, if any).
# Looks for stanza boundaries — `\n\n[stanza-name]` — and inserts before them.
def _inject_rba(text: str, block: str) -> str:
    if not block:
        return text
    # Strategy: split on stanza headers, append block to each non-empty
    # body. Keeps the source file's hand-authored content unchanged.
    parts = re.split(r"(?m)^(\[[^\]]+\]\s*\n)", text)
    if len(parts) < 3:
        return text + ("\n" if not text.endswith("\n") else "") + block
    out_chunks: list[str] = [parts[0]]
    for i in range(1, len(parts), 2):
        header = parts[i]
        body = parts[i + 1] if i + 1 < len(parts) else ""
        # Strip trailing whitespace from body, append RBA block, then 1 blank line.
        body = body.rstrip() + "\n" + block + "\n"
        out_chunks.append(header + body)
    return "".join(out_chunks)


# Stanza header parser for case metadata extraction (technique/tactic/severity from macros).
_STANZA_RE = re.compile(r"^\[(?P<name>[^\]]+)\]\s*$")
_EVAL_FIELD_RE = re.compile(
    r'\b(?P<key>case_id|case_title|view_name|mitre_technique|mitre_tactic|severity)'
    r'\s*=\s*"(?P<val>[^"]+)"'
)


def _parse_case_metadata(macro_text: str) -> dict:
    """Extract case_id/title/technique/tactic/severity from per-case macro eval lines."""
    fields: dict[str, str] = {}
    for m in _EVAL_FIELD_RE.finditer(macro_text):
        # First match wins per key — top-of-stanza eval is the canonical one.
        fields.setdefault(m.group("key"), m.group("val"))
    return fields


def build_cases_lookup() -> str:
    """Generate detlab_cases.csv from each case's macros.conf eval metadata.

    Columns sourced from macros.conf: case_id, case_title, view_name,
    mitre_technique, mitre_tactic, severity. Columns sourced from
    `case_metadata.CASE_METADATA`: risk_score, risk_object_type,
    pyramid_tier, threat_groups (semicolon-joined), data_sources
    (semicolon-joined). The lookup feeds Splunk RBA savedsearches and
    SOAR playbook routers, so Splunk-side queries can filter / sort /
    join on every dimension."""
    rows = []
    for case in _case_dirs():
        macro_text = _read(case / "detection" / "macros.conf")
        meta = _parse_case_metadata(macro_text)
        case_id = meta.get("case_id") or case.name
        extras = CASE_METADATA.get(case_id, {})
        rows.append(
            {
                "case_id": case_id,
                "case_title": meta.get("case_title", case_id),
                "view_name": meta.get("view_name", ""),
                "mitre_technique": meta.get("mitre_technique", ""),
                "mitre_tactic": meta.get("mitre_tactic", ""),
                "severity": meta.get("severity", "medium"),
                "status": "shipped",
                "risk_score": extras.get("risk_score", 0),
                "risk_object_type": extras.get("risk_object_type", "system"),
                "pyramid_tier": extras.get("pyramid_tier", 0),
                "threat_groups": ";".join(extras.get("threat_groups", [])),
                "data_sources": ";".join(extras.get("data_sources", [])),
            }
        )
    buf = io.StringIO()
    fieldnames = [
        "case_id",
        "case_title",
        "view_name",
        "mitre_technique",
        "mitre_tactic",
        "severity",
        "status",
        "risk_score",
        "risk_object_type",
        "pyramid_tier",
        "threat_groups",
        "data_sources",
    ]
    writer = csv.DictWriter(buf, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def update_app_version(target_path: Path, version: str) -> None:
    """Sync app.conf version line with pyproject.toml."""
    text = target_path.read_text(encoding="utf-8")
    new = re.sub(r"^version\s*=.*$", f"version = {version}", text, count=1, flags=re.MULTILINE)
    if new != text:
        target_path.write_text(new, encoding="utf-8")


# ---------- Splunk ES integration generators ----------
#
# When the .spl is installed alongside Splunk Enterprise Security, these conf
# files surface detlab content in ES's standard places:
#   * correlationsearches.conf   — ES Incident Review picks up each saved search
#   * analyticstories.conf       — group rules into MITRE-tactic stories
#   * eventtypes.conf + tags.conf — CIM-tag the alert events so data models pick
#                                   them up automatically

# Saved-search stanza headers we extract from per-case savedsearches.conf so
# correlationsearches/analyticstories can reference them by name. Allows
# parens in the title — Splunk does, e.g. "[Remote Access Software (RMM) — …]".
_SAVEDSEARCH_STANZA_RE = re.compile(r"^\[(?P<name>[^\]]+)\]\s*$", re.MULTILINE)


def _saved_search_names_for(case_dir: Path) -> list[str]:
    """Return the saved-search stanza names declared by a case's savedsearches.conf."""
    text = _read(case_dir / "detection" / "savedsearches.conf")
    return _SAVEDSEARCH_STANZA_RE.findall(text)


def build_correlationsearches() -> str:
    """Generate correlationsearches.conf so Splunk ES picks up every saved search.

    ES expects one stanza per saved-search name with metadata about how the
    rule should appear in Incident Review. We pull `case_title`,
    `mitre_technique`, `mitre_tactic`, `severity` from the per-case macros
    and stamp it into each stanza."""
    chunks = [GENERATED_BANNER]
    for case_dir in _case_dirs():
        meta = _parse_case_metadata(_read(case_dir / "detection" / "macros.conf"))
        for ss in _saved_search_names_for(case_dir):
            chunks.append(f"[{ss}]\n")
            chunks.append(
                f"description = detlab — {meta.get('mitre_technique', '')} "
                f"({meta.get('mitre_tactic', '')}). {meta.get('case_title', case_dir.name)}.\n"
            )
            chunks.append(
                "how_to_implement = Install the detlab app and ensure Zeek "
                "(plus optional Suricata) telemetry reaches the matching indexes.\n"
            )
            chunks.append(
                "known_false_positives = "
                f"See cases/{case_dir.name}/README.md for the full FP catalogue.\n"
            )
            technique = meta.get("mitre_technique", "")
            chunks.append(f'annotations = {{"mitre_attack": ["{technique}"]}}\n')
            chunks.append("nes_fields = src,dest,case_id\n")
            chunks.append("\n")
    return "".join(chunks)


# MITRE tactic → analytic-story title used in Splunk ES.
_TACTIC_STORY_TITLE = {
    "command-and-control": "Command and Control",
    "credential-access": "Credential Access",
    "discovery": "Discovery",
    "exfiltration": "Exfiltration",
    "impact": "Impact",
    "initial-access": "Initial Access",
    "lateral-movement": "Lateral Movement",
}


def build_analyticstories() -> str:
    """Generate analyticstories.conf grouping correlation searches by ATT&CK tactic.

    One story per tactic that has at least one shipped case. Each story lists
    its detection_searches (saved-search names from the per-case
    savedsearches.conf)."""
    chunks = [GENERATED_BANNER]
    by_tactic: dict[str, list[str]] = {}
    for case_dir in _case_dirs():
        meta = _parse_case_metadata(_read(case_dir / "detection" / "macros.conf"))
        tactic = meta.get("mitre_tactic", "")
        if not tactic:
            continue
        for ss in _saved_search_names_for(case_dir):
            by_tactic.setdefault(tactic, []).append(ss)

    for tactic in sorted(by_tactic):
        story = f"detlab — {_TACTIC_STORY_TITLE.get(tactic, tactic.title())}"
        rules = sorted(set(by_tactic[tactic]))
        chunks.append(f"[{story}]\n")
        chunks.append(
            f"description = detlab detections grouped by the {tactic} tactic. "
            "Each rule pairs a reproducible attack with the SPL macro that "
            "catches it on real Zeek/Suricata telemetry.\n"
        )
        chunks.append("category = Network Compromise\n")
        chunks.append(
            "narrative = See cases/ in github.com/JacobRHess/detlab for "
            "the full per-case narrative.\n"
        )
        chunks.append(f"detection_searches = {', '.join(rules)}\n")
        tactic_url = f"https://attack.mitre.org/tactics/{tactic.upper().replace('-', '_')}/"
        chunks.append(f"references = {tactic_url}, https://github.com/JacobRHess/detlab\n")
        chunks.append("\n")
    return "".join(chunks)


def build_eventtypes() -> str:
    """Group detlab alert outputs into named eventtypes for CIM tagging.

    `detlab_alert` matches every alert from any case (used for the
    Network_Traffic / Network_Resolution / IDS data models depending on
    tags). Per-tactic eventtypes give SOC analysts ready-made pivot points.
    """
    chunks = [GENERATED_BANNER]
    chunks.append("[detlab_alert]\n")
    chunks.append("search = `detlab_all_alerts`\n")
    chunks.append("description = Any alert produced by any detlab detection.\n\n")

    seen_tactics: set[str] = set()
    for case_dir in _case_dirs():
        meta = _parse_case_metadata(_read(case_dir / "detection" / "macros.conf"))
        tactic = meta.get("mitre_tactic", "")
        if not tactic or tactic in seen_tactics:
            continue
        seen_tactics.add(tactic)
        slug = tactic.replace("-", "_")
        chunks.append(f"[detlab_{slug}_alert]\n")
        chunks.append(
            f"search = `detlab_all_alerts` mitre_tactic=\"{tactic}\"\n"
        )
        chunks.append(
            f"description = detlab alerts in the {tactic} ATT&CK tactic.\n\n"
        )
    return "".join(chunks)


def build_workflow_actions() -> str:
    """Generate workflow_actions.conf — right-click pivot actions in
    Splunk dashboards. Each action shows up in the "Event Actions" menu
    when an analyst inspects an alert, giving instant pivots for the
    common SOC questions: "what else has this src done?", "open the
    technique page on attack.mitre.org", etc."""
    chunks = [GENERATED_BANNER]

    # Pivot: search all events from this src in the last 24h.
    chunks.append("[detlab_pivot_src]\n")
    chunks.append("display_location = both\n")
    chunks.append("type             = search\n")
    chunks.append("label            = detlab — search all events from $src$ (24h)\n")
    chunks.append("fields           = src\n")
    chunks.append('search_string    = index=zeek OR index=suricata src="$src$"\n')
    chunks.append("search_view      = search\n")
    chunks.append("search_earliest  = -24h\n")
    chunks.append("search_latest    = now\n\n")

    # Pivot: search all detlab alerts for this src in the last 7 days.
    chunks.append("[detlab_pivot_src_alerts]\n")
    chunks.append("display_location = both\n")
    chunks.append("type             = search\n")
    chunks.append("label            = detlab — all detlab alerts for $src$ (7d)\n")
    chunks.append("fields           = src\n")
    chunks.append('search_string    = `detlab_all_alerts` src="$src$"\n')
    chunks.append("search_view      = search\n")
    chunks.append("search_earliest  = -7d\n")
    chunks.append("search_latest    = now\n\n")

    # Pivot: search all events to this dest in the last 24h.
    chunks.append("[detlab_pivot_dest]\n")
    chunks.append("display_location = both\n")
    chunks.append("type             = search\n")
    chunks.append("label            = detlab — search all events to $dest$ (24h)\n")
    chunks.append("fields           = dest\n")
    chunks.append('search_string    = index=zeek OR index=suricata dest="$dest$"\n')
    chunks.append("search_view      = search\n")
    chunks.append("search_earliest  = -24h\n")
    chunks.append("search_latest    = now\n\n")

    # External: open the ATT&CK technique page.
    chunks.append("[detlab_pivot_attack_mitre]\n")
    chunks.append("display_location = both\n")
    chunks.append("type             = link\n")
    chunks.append("label            = detlab — open ATT&CK $mitre_technique$ on attack.mitre.org\n")
    chunks.append("fields           = mitre_technique\n")
    chunks.append("link.uri         = https://attack.mitre.org/techniques/$mitre_technique$/\n")
    chunks.append("link.target      = blank\n")
    chunks.append("link.method      = get\n\n")

    # External: open the case source on GitHub.
    chunks.append("[detlab_pivot_case_source]\n")
    chunks.append("display_location = both\n")
    chunks.append("type             = link\n")
    chunks.append("label            = detlab — open case source on GitHub\n")
    chunks.append("fields           = case_id\n")
    chunks.append("link.uri         = https://github.com/JacobRHess/detlab/tree/main/cases/$case_id$\n")
    chunks.append("link.target      = blank\n")
    chunks.append("link.method      = get\n\n")

    return "".join(chunks)


def build_tags() -> str:
    """Apply CIM tags to detlab eventtypes so the alerts plug into Splunk ES
    data models without further configuration."""
    chunks = [GENERATED_BANNER]
    # Every detlab alert is a CIM "alert" event.
    chunks.append("[eventtype=detlab_alert]\n")
    chunks.append("alert = enabled\n")
    chunks.append("attack = enabled\n")
    chunks.append("\n")

    # Per-tactic CIM tags. Network_Traffic for connection-style alerts;
    # Network_Resolution for DNS-driven ones; IDS for Suricata.
    cim_per_tactic = {
        "command-and-control": ["network", "ids_attack"],
        "credential-access": ["authentication"],
        "discovery": ["network"],
        "exfiltration": ["network", "ids_attack"],
        "impact": ["network", "ids_attack"],
        "initial-access": ["ids_attack", "attack"],
    }
    for tactic, cim_tags in cim_per_tactic.items():
        slug = tactic.replace("-", "_")
        chunks.append(f"[eventtype=detlab_{slug}_alert]\n")
        for tag in cim_tags:
            chunks.append(f"{tag} = enabled\n")
        chunks.append("\n")
    return "".join(chunks)


# ---------- Validation + write ----------


def get_version() -> str:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    return tomllib.loads(pyproject)["project"]["version"]


def _strip_comments(text: str) -> str:
    """Drop lines that start with `#` so the macro-reference scanner doesn't
    match backtick-wrapped words inside comments. Keeps blank lines so line
    numbers are stable for diff debugging."""
    return "\n".join("" if ln.lstrip().startswith("#") else ln for ln in text.splitlines())


def validate(macros: str, savedsearches: str, cases_csv: str) -> list[str]:
    """Sanity checks: every saved search references a defined macro; cases lookup non-empty."""
    errors: list[str] = []
    macro_names = set(re.findall(r"^\[(?P<n>[^\]\(]+)(?:\([^\)]*\))?\]", macros, re.MULTILINE))
    referenced = set(re.findall(r"`([a-zA-Z0-9_]+)`", _strip_comments(savedsearches)))
    missing = referenced - macro_names
    if missing:
        errors.append(f"savedsearches reference undefined macros: {sorted(missing)}")
    if cases_csv.count("\n") < 2:  # header + at least one case
        errors.append("detlab_cases.csv has no case rows — did you add a case under cases/?")
    return errors


def write_outputs(
    macros: str,
    savedsearches: str,
    cases_csv: str,
    *,
    correlationsearches: str = "",
    analyticstories: str = "",
    eventtypes: str = "",
    tags: str = "",
    workflow_actions: str = "",
) -> None:
    APP_DEFAULT.mkdir(parents=True, exist_ok=True)
    APP_LOOKUPS.mkdir(parents=True, exist_ok=True)
    (APP_DEFAULT / "macros.conf").write_text(macros, encoding="utf-8")
    (APP_DEFAULT / "savedsearches.conf").write_text(savedsearches, encoding="utf-8")
    (APP_LOOKUPS / "detlab_cases.csv").write_text(cases_csv, encoding="utf-8")
    if correlationsearches:
        (APP_DEFAULT / "correlationsearches.conf").write_text(correlationsearches, encoding="utf-8")
    if analyticstories:
        (APP_DEFAULT / "analyticstories.conf").write_text(analyticstories, encoding="utf-8")
    if eventtypes:
        (APP_DEFAULT / "eventtypes.conf").write_text(eventtypes, encoding="utf-8")
    if tags:
        (APP_DEFAULT / "tags.conf").write_text(tags, encoding="utf-8")
    if workflow_actions:
        (APP_DEFAULT / "workflow_actions.conf").write_text(workflow_actions, encoding="utf-8")


def package_app(version: str) -> Path:
    """Tar the app/ directory into build/detlab-<version>.tar.gz."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    out = BUILD_DIR / f"detlab-{version}.tar.gz"
    if out.exists():
        out.unlink()

    with tarfile.open(out, "w:gz") as tar:
        # Splunk apps are conventionally packaged with a top-level dir named after the app.
        tar.add(APP_DIR, arcname="detlab", filter=_skip_pycache)
    return out


def _skip_pycache(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
    if "/__pycache__" in info.name or info.name.endswith(".pyc"):
        return None
    return info


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the detlab Splunk app.")
    parser.add_argument(
        "--no-package", action="store_true", help="Generate confs/lookup only; skip tarball."
    )
    args = parser.parse_args(argv)

    version = get_version()
    print(f"detlab build — version {version}")

    macros = build_macros()
    savedsearches = build_savedsearches()
    cases_csv = build_cases_lookup()
    correlationsearches = build_correlationsearches()
    analyticstories = build_analyticstories()
    eventtypes = build_eventtypes()
    tags = build_tags()
    workflow_actions = build_workflow_actions()

    errors = validate(macros, savedsearches, cases_csv)
    if errors:
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        return 2

    write_outputs(
        macros,
        savedsearches,
        cases_csv,
        correlationsearches=correlationsearches,
        analyticstories=analyticstories,
        eventtypes=eventtypes,
        tags=tags,
        workflow_actions=workflow_actions,
    )
    update_app_version(APP_DEFAULT / "app.conf", version)

    n_cases = cases_csv.count("\n") - 1
    n_correlations = sum(1 for ln in correlationsearches.splitlines() if ln.startswith("["))
    n_stories = sum(1 for ln in analyticstories.splitlines() if ln.startswith("["))
    print(f"  wrote app/default/macros.conf ({len(macros):,} bytes)")
    print(f"  wrote app/default/savedsearches.conf ({len(savedsearches):,} bytes)")
    print(f"  wrote app/lookups/detlab_cases.csv ({n_cases} cases)")
    print(f"  wrote app/default/correlationsearches.conf ({n_correlations} ES correlations)")
    print(f"  wrote app/default/analyticstories.conf ({n_stories} ATT&CK stories)")
    print("  wrote app/default/eventtypes.conf + tags.conf (CIM tags for ES data models)")
    print("  wrote app/default/workflow_actions.conf (SOC pivot actions)")

    if args.no_package:
        return 0

    out = package_app(version)
    try:
        display_path = out.relative_to(ROOT)
    except ValueError:
        display_path = out  # tarball lives outside the repo (e.g. CI tmp dir)
    print(f"  packaged -> {display_path} ({out.stat().st_size / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
