"""Build the deployable Splunk app from per-case detections.

Walks `cases/<id>/detection/` directories, concatenates the per-case
`savedsearches.conf` and `macros.conf` into the app under
`app/default/`, generates a `detlab_cases.csv` lookup that the dashboards
read, validates the result, and packages the whole app as a `.spl` tarball
under `build/`.

Usage:
    py scripts/build_app.py
    py scripts/build_app.py --no-package    # generate confs only
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import tarfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CASES_DIR = ROOT / "cases"
SHARED_DIR = ROOT / "shared"
APP_DIR = ROOT / "app"
APP_DEFAULT = APP_DIR / "default"
APP_LOOKUPS = APP_DIR / "lookups"
BUILD_DIR = ROOT / "build"

GENERATED_BANNER = (
    "# !!! GENERATED BY scripts/build_app.py — DO NOT EDIT BY HAND !!!\n"
    "# Source of truth: shared/{macros,savedsearches}.conf and cases/*/detection/.\n\n"
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _case_dirs() -> list[Path]:
    return sorted(d for d in CASES_DIR.iterdir() if d.is_dir() and (d / "detection").is_dir())


def build_macros() -> str:
    """Concatenate shared/macros.conf + cases/*/detection/macros.conf."""
    chunks = [GENERATED_BANNER]
    shared = _read(SHARED_DIR / "macros.conf")
    if shared:
        chunks.append("# === shared/macros.conf ===\n" + shared.strip() + "\n\n")
    for case in _case_dirs():
        m = _read(case / "detection" / "macros.conf")
        if m:
            chunks.append(f"# === cases/{case.name}/detection/macros.conf ===\n")
            chunks.append(m.strip() + "\n\n")
    return "".join(chunks)


def build_savedsearches() -> str:
    """Concatenate cases/*/detection/savedsearches.conf."""
    chunks = [GENERATED_BANNER]
    for case in _case_dirs():
        s = _read(case / "detection" / "savedsearches.conf")
        if s:
            chunks.append(f"# === cases/{case.name}/detection/savedsearches.conf ===\n")
            chunks.append(s.strip() + "\n\n")
    return "".join(chunks)


# Stanza header parser for case metadata extraction (technique/tactic/severity from macros).
_STANZA_RE = re.compile(r"^\[(?P<name>[^\]]+)\]\s*$")
_EVAL_FIELD_RE = re.compile(
    r'\b(?P<key>case_id|case_title|view_name|mitre_technique|mitre_tactic|severity)'
    r'\s*=\s*"(?P<val>[^"]+)"'
)


def _parse_case_metadata(macro_text: str) -> dict:
    """Extract case_id/title/technique/tactic/severity from per-case macro eval lines."""
    fields: dict[str, str] = {}
    for m in _EVAL_FIELD_RE.finditer(macro_text):
        # First match wins per key — top-of-stanza eval is the canonical one.
        fields.setdefault(m.group("key"), m.group("val"))
    return fields


def build_cases_lookup() -> str:
    """Generate detlab_cases.csv from each case's macros.conf eval metadata."""
    rows = []
    for case in _case_dirs():
        macro_text = _read(case / "detection" / "macros.conf")
        meta = _parse_case_metadata(macro_text)
        case_id = meta.get("case_id") or case.name
        rows.append(
            {
                "case_id": case_id,
                "case_title": meta.get("case_title", case_id),
                "view_name": meta.get("view_name", ""),
                "mitre_technique": meta.get("mitre_technique", ""),
                "mitre_tactic": meta.get("mitre_tactic", ""),
                "severity": meta.get("severity", "medium"),
                "status": "shipped",
            }
        )
    buf = io.StringIO()
    fieldnames = [
        "case_id",
        "case_title",
        "view_name",
        "mitre_technique",
        "mitre_tactic",
        "severity",
        "status",
    ]
    writer = csv.DictWriter(buf, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def update_app_version(target_path: Path, version: str) -> None:
    """Sync app.conf version line with pyproject.toml."""
    text = target_path.read_text(encoding="utf-8")
    new = re.sub(r"^version\s*=.*$", f"version = {version}", text, count=1, flags=re.MULTILINE)
    if new != text:
        target_path.write_text(new, encoding="utf-8")


def get_version() -> str:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    return tomllib.loads(pyproject)["project"]["version"]


def validate(macros: str, savedsearches: str, cases_csv: str) -> list[str]:
    """Sanity checks: every saved search references a defined macro; cases lookup non-empty."""
    errors: list[str] = []
    macro_names = set(re.findall(r"^\[(?P<n>[^\]\(]+)(?:\([^\)]*\))?\]", macros, re.MULTILINE))
    referenced = set(re.findall(r"`([a-zA-Z0-9_]+)`", savedsearches))
    missing = referenced - macro_names
    if missing:
        errors.append(f"savedsearches reference undefined macros: {sorted(missing)}")
    if cases_csv.count("\n") < 2:  # header + at least one case
        errors.append("detlab_cases.csv has no case rows — did you add a case under cases/?")
    return errors


def write_outputs(macros: str, savedsearches: str, cases_csv: str) -> None:
    APP_DEFAULT.mkdir(parents=True, exist_ok=True)
    APP_LOOKUPS.mkdir(parents=True, exist_ok=True)
    (APP_DEFAULT / "macros.conf").write_text(macros, encoding="utf-8")
    (APP_DEFAULT / "savedsearches.conf").write_text(savedsearches, encoding="utf-8")
    (APP_LOOKUPS / "detlab_cases.csv").write_text(cases_csv, encoding="utf-8")


def package_app(version: str) -> Path:
    """Tar the app/ directory into build/detlab-<version>.tar.gz."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    out = BUILD_DIR / f"detlab-{version}.tar.gz"
    if out.exists():
        out.unlink()

    with tarfile.open(out, "w:gz") as tar:
        # Splunk apps are conventionally packaged with a top-level dir named after the app.
        tar.add(APP_DIR, arcname="detlab", filter=_skip_pycache)
    return out


def _skip_pycache(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
    if "/__pycache__" in info.name or info.name.endswith(".pyc"):
        return None
    return info


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the detlab Splunk app.")
    parser.add_argument(
        "--no-package", action="store_true", help="Generate confs/lookup only; skip tarball."
    )
    args = parser.parse_args(argv)

    version = get_version()
    print(f"detlab build — version {version}")

    macros = build_macros()
    savedsearches = build_savedsearches()
    cases_csv = build_cases_lookup()

    errors = validate(macros, savedsearches, cases_csv)
    if errors:
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        return 2

    write_outputs(macros, savedsearches, cases_csv)
    update_app_version(APP_DEFAULT / "app.conf", version)

    n_cases = cases_csv.count("\n") - 1
    print(f"  wrote app/default/macros.conf ({len(macros):,} bytes)")
    print(f"  wrote app/default/savedsearches.conf ({len(savedsearches):,} bytes)")
    print(f"  wrote app/lookups/detlab_cases.csv ({n_cases} cases)")

    if args.no_package:
        return 0

    out = package_app(version)
    try:
        display_path = out.relative_to(ROOT)
    except ValueError:
        display_path = out  # tarball lives outside the repo (e.g. CI tmp dir)
    print(f"  packaged -> {display_path} ({out.stat().st_size / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
